//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Amonestacion_x_Empleado
    {
        public int id_amonestacion_x_empleado { get; set; }
        public int id_amonestacion { get; set; }
        public int id_empleado { get; set; }
        public string descripcion { get; set; }
        public bool activo { get; set; }
        public System.DateTime fecha { get; set; }
    
        public virtual Amonestacion Amonestacion { get; set; }
        public virtual Empleado Empleado { get; set; }
    }
}
