//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aspecto_Tecnico
    {
        public int id_aspecto_tecnico { get; set; }
        public string descripcion { get; set; }
        public bool activo { get; set; }
    }
}
