//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Departamento_x_Ferreteria
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Departamento_x_Ferreteria()
        {
            this.Pasillo_x_Departamento = new HashSet<Pasillo_x_Departamento>();
        }
    
        public int id_departamento_x_ferreteria { get; set; }
        public int id_departamento { get; set; }
        public int id_ferreteria { get; set; }
        public int id_experto { get; set; }
        public bool activo { get; set; }
    
        public virtual Departamento Departamento { get; set; }
        public virtual Empleado Empleado { get; set; }
        public virtual Ferreteria Ferreteria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pasillo_x_Departamento> Pasillo_x_Departamento { get; set; }
    }
}
