//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Empleado()
        {
            this.Amonestacion_x_Empleado = new HashSet<Amonestacion_x_Empleado>();
            this.Departamento_x_Ferreteria = new HashSet<Departamento_x_Ferreteria>();
            this.Empleado_x_Ferreteria = new HashSet<Empleado_x_Ferreteria>();
            this.Lista_Deseos = new HashSet<Lista_Deseos>();
            this.Venta = new HashSet<Venta>();
        }
    
        public int id_empleado { get; set; }
        public int id_tipo_empleado { get; set; }
        public string nombre { get; set; }
        public System.DateTime fecha_ingreso { get; set; }
        public int carnet { get; set; }
        public decimal salario { get; set; }
        public int vacaciones { get; set; }
        public bool activo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Amonestacion_x_Empleado> Amonestacion_x_Empleado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Departamento_x_Ferreteria> Departamento_x_Ferreteria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Empleado_x_Ferreteria> Empleado_x_Ferreteria { get; set; }
        public virtual Tipo_Empleado Tipo_Empleado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lista_Deseos> Lista_Deseos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Venta> Venta { get; set; }
    }
}
