//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleado_x_Ferreteria
    {
        public int id_empleado_x_ferreteria { get; set; }
        public int id_empleado { get; set; }
        public int id_ferreteria { get; set; }
        public bool activo { get; set; }
    
        public virtual Empleado Empleado { get; set; }
        public virtual Ferreteria Ferreteria { get; set; }
    }
}
