//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lista_Deseos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Lista_Deseos()
        {
            this.Detalle_Lista_Deseos = new HashSet<Detalle_Lista_Deseos>();
        }
    
        public int id_lista { get; set; }
        public int id_cliente { get; set; }
        public int id_vendedor { get; set; }
        public System.DateTime fecha { get; set; }
        public bool entregado { get; set; }
        public bool activo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detalle_Lista_Deseos> Detalle_Lista_Deseos { get; set; }
        public virtual Empleado Empleado { get; set; }
    }
}
