//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class FerreteriaOnlineEntities1 : DbContext
    {
        public FerreteriaOnlineEntities1()
            : base("name=FerreteriaOnlineEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Amonestacion> Amonestacion { get; set; }
        public virtual DbSet<Amonestacion_x_Empleado> Amonestacion_x_Empleado { get; set; }
        public virtual DbSet<Aspecto_Tecnico> Aspecto_Tecnico { get; set; }
        public virtual DbSet<Bodega> Bodega { get; set; }
        public virtual DbSet<Contraindicacion> Contraindicacion { get; set; }
        public virtual DbSet<Cuidado> Cuidado { get; set; }
        public virtual DbSet<Departamento> Departamento { get; set; }
        public virtual DbSet<Departamento_x_Ferreteria> Departamento_x_Ferreteria { get; set; }
        public virtual DbSet<Detalle_Lista_Deseos> Detalle_Lista_Deseos { get; set; }
        public virtual DbSet<Detalle_Venta> Detalle_Venta { get; set; }
        public virtual DbSet<Empleado> Empleado { get; set; }
        public virtual DbSet<Empleado_x_Ferreteria> Empleado_x_Ferreteria { get; set; }
        public virtual DbSet<Estante> Estante { get; set; }
        public virtual DbSet<Ferreteria> Ferreteria { get; set; }
        public virtual DbSet<Garantia> Garantia { get; set; }
        public virtual DbSet<Inventario_Bodega> Inventario_Bodega { get; set; }
        public virtual DbSet<Inventario_Ferreteria> Inventario_Ferreteria { get; set; }
        public virtual DbSet<Lista_Deseos> Lista_Deseos { get; set; }
        public virtual DbSet<Marca> Marca { get; set; }
        public virtual DbSet<Pasillo> Pasillo { get; set; }
        public virtual DbSet<Pasillo_x_Departamento> Pasillo_x_Departamento { get; set; }
        public virtual DbSet<Producto> Producto { get; set; }
        public virtual DbSet<Producto_x_Estante> Producto_x_Estante { get; set; }
        public virtual DbSet<ProductoDetalles> ProductoDetalles { get; set; }
        public virtual DbSet<Proveedor> Proveedor { get; set; }
        public virtual DbSet<Tipo_Empleado> Tipo_Empleado { get; set; }
        public virtual DbSet<Tipo_venta> Tipo_venta { get; set; }
        public virtual DbSet<Utilidad> Utilidad { get; set; }
        public virtual DbSet<Vacaciones_disfrutadas> Vacaciones_disfrutadas { get; set; }
        public virtual DbSet<Venta> Venta { get; set; }
    
        public virtual int Crear_Amonestacion(string indescripcion)
        {
            var indescripcionParameter = indescripcion != null ?
                new ObjectParameter("indescripcion", indescripcion) :
                new ObjectParameter("indescripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Crear_Amonestacion", indescripcionParameter);
        }
    
        public virtual int Crear_Amonestacion_x_Empleado(string innombre_amonestacion, Nullable<int> incarnet_empleado, string indescripcion)
        {
            var innombre_amonestacionParameter = innombre_amonestacion != null ?
                new ObjectParameter("innombre_amonestacion", innombre_amonestacion) :
                new ObjectParameter("innombre_amonestacion", typeof(string));
    
            var incarnet_empleadoParameter = incarnet_empleado.HasValue ?
                new ObjectParameter("incarnet_empleado", incarnet_empleado) :
                new ObjectParameter("incarnet_empleado", typeof(int));
    
            var indescripcionParameter = indescripcion != null ?
                new ObjectParameter("indescripcion", indescripcion) :
                new ObjectParameter("indescripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Crear_Amonestacion_x_Empleado", innombre_amonestacionParameter, incarnet_empleadoParameter, indescripcionParameter);
        }
    
        public virtual int Crear_Aspecto_Tecnico(string indescripcion)
        {
            var indescripcionParameter = indescripcion != null ?
                new ObjectParameter("indescripcion", indescripcion) :
                new ObjectParameter("indescripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Crear_Aspecto_Tecnico", indescripcionParameter);
        }
    
        public virtual int Crear_Aspecto_Tecnico_x_Producto(string innombre_producto, string indescripcion_aspecto_tecnico)
        {
            var innombre_productoParameter = innombre_producto != null ?
                new ObjectParameter("innombre_producto", innombre_producto) :
                new ObjectParameter("innombre_producto", typeof(string));
    
            var indescripcion_aspecto_tecnicoParameter = indescripcion_aspecto_tecnico != null ?
                new ObjectParameter("indescripcion_aspecto_tecnico", indescripcion_aspecto_tecnico) :
                new ObjectParameter("indescripcion_aspecto_tecnico", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Crear_Aspecto_Tecnico_x_Producto", innombre_productoParameter, indescripcion_aspecto_tecnicoParameter);
        }
    
        public virtual int Crear_Bodega(string indescripcion, System.Data.Entity.Spatial.DbGeometry in_ubicacion)
        {
            var indescripcionParameter = indescripcion != null ?
                new ObjectParameter("indescripcion", indescripcion) :
                new ObjectParameter("indescripcion", typeof(string));
    
            var in_ubicacionParameter = in_ubicacion != null ?
                new ObjectParameter("in_ubicacion", in_ubicacion) :
                new ObjectParameter("in_ubicacion", typeof(System.Data.Entity.Spatial.DbGeometry));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Crear_Bodega", indescripcionParameter, in_ubicacionParameter);
        }
    
        public virtual int Crear_Cliente(string innombre, Nullable<int> inpuntuacion, string incorreo, Nullable<int> metodo_Pago)
        {
            var innombreParameter = innombre != null ?
                new ObjectParameter("innombre", innombre) :
                new ObjectParameter("innombre", typeof(string));
    
            var inpuntuacionParameter = inpuntuacion.HasValue ?
                new ObjectParameter("inpuntuacion", inpuntuacion) :
                new ObjectParameter("inpuntuacion", typeof(int));
    
            var incorreoParameter = incorreo != null ?
                new ObjectParameter("incorreo", incorreo) :
                new ObjectParameter("incorreo", typeof(string));
    
            var metodo_PagoParameter = metodo_Pago.HasValue ?
                new ObjectParameter("metodo_Pago", metodo_Pago) :
                new ObjectParameter("metodo_Pago", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Crear_Cliente", innombreParameter, inpuntuacionParameter, incorreoParameter, metodo_PagoParameter);
        }
    
        public virtual int Crear_Cliente_x_Ferreteria(string innombre_cliente, string innombre_ferreteria)
        {
            var innombre_clienteParameter = innombre_cliente != null ?
                new ObjectParameter("innombre_cliente", innombre_cliente) :
                new ObjectParameter("innombre_cliente", typeof(string));
    
            var innombre_ferreteriaParameter = innombre_ferreteria != null ?
                new ObjectParameter("innombre_ferreteria", innombre_ferreteria) :
                new ObjectParameter("innombre_ferreteria", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Crear_Cliente_x_Ferreteria", innombre_clienteParameter, innombre_ferreteriaParameter);
        }
    
        public virtual int Crear_contraindicacion(string indescripcion)
        {
            var indescripcionParameter = indescripcion != null ?
                new ObjectParameter("indescripcion", indescripcion) :
                new ObjectParameter("indescripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Crear_contraindicacion", indescripcionParameter);
        }
    
        public virtual int Crear_Contraindicacion_x_Producto(string innombre_producto, string indescripcion_contraindicacion)
        {
            var innombre_productoParameter = innombre_producto != null ?
                new ObjectParameter("innombre_producto", innombre_producto) :
                new ObjectParameter("innombre_producto", typeof(string));
    
            var indescripcion_contraindicacionParameter = indescripcion_contraindicacion != null ?
                new ObjectParameter("indescripcion_contraindicacion", indescripcion_contraindicacion) :
                new ObjectParameter("indescripcion_contraindicacion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Crear_Contraindicacion_x_Producto", innombre_productoParameter, indescripcion_contraindicacionParameter);
        }
    
        public virtual int Crear_Cuidado(string indescripcion)
        {
            var indescripcionParameter = indescripcion != null ?
                new ObjectParameter("indescripcion", indescripcion) :
                new ObjectParameter("indescripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Crear_Cuidado", indescripcionParameter);
        }
    
        public virtual int Crear_Cuidado_x_Producto(string innombre_producto, string indescripcion_cuidado)
        {
            var innombre_productoParameter = innombre_producto != null ?
                new ObjectParameter("innombre_producto", innombre_producto) :
                new ObjectParameter("innombre_producto", typeof(string));
    
            var indescripcion_cuidadoParameter = indescripcion_cuidado != null ?
                new ObjectParameter("indescripcion_cuidado", indescripcion_cuidado) :
                new ObjectParameter("indescripcion_cuidado", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Crear_Cuidado_x_Producto", innombre_productoParameter, indescripcion_cuidadoParameter);
        }
    
        public virtual int Crear_Departamento(string indescripcion)
        {
            var indescripcionParameter = indescripcion != null ?
                new ObjectParameter("indescripcion", indescripcion) :
                new ObjectParameter("indescripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Crear_Departamento", indescripcionParameter);
        }
    
        public virtual int Crear_Departamento_x_Ferreteria(string innombre_ferreteria, string indescripdepartamento, Nullable<int> incarnet_empleado)
        {
            var innombre_ferreteriaParameter = innombre_ferreteria != null ?
                new ObjectParameter("innombre_ferreteria", innombre_ferreteria) :
                new ObjectParameter("innombre_ferreteria", typeof(string));
    
            var indescripdepartamentoParameter = indescripdepartamento != null ?
                new ObjectParameter("indescripdepartamento", indescripdepartamento) :
                new ObjectParameter("indescripdepartamento", typeof(string));
    
            var incarnet_empleadoParameter = incarnet_empleado.HasValue ?
                new ObjectParameter("incarnet_empleado", incarnet_empleado) :
                new ObjectParameter("incarnet_empleado", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Crear_Departamento_x_Ferreteria", innombre_ferreteriaParameter, indescripdepartamentoParameter, incarnet_empleadoParameter);
        }
    
        public virtual int Crear_Detalle_Venta(string innombre_cliente, Nullable<int> incarnet_empleado, string innombre_ferreteria, Nullable<System.DateTime> infecha, Nullable<decimal> inmonto, Nullable<int> incodigo_producto, Nullable<int> incantidad_producto)
        {
            var innombre_clienteParameter = innombre_cliente != null ?
                new ObjectParameter("innombre_cliente", innombre_cliente) :
                new ObjectParameter("innombre_cliente", typeof(string));
    
            var incarnet_empleadoParameter = incarnet_empleado.HasValue ?
                new ObjectParameter("incarnet_empleado", incarnet_empleado) :
                new ObjectParameter("incarnet_empleado", typeof(int));
    
            var innombre_ferreteriaParameter = innombre_ferreteria != null ?
                new ObjectParameter("innombre_ferreteria", innombre_ferreteria) :
                new ObjectParameter("innombre_ferreteria", typeof(string));
    
            var infechaParameter = infecha.HasValue ?
                new ObjectParameter("infecha", infecha) :
                new ObjectParameter("infecha", typeof(System.DateTime));
    
            var inmontoParameter = inmonto.HasValue ?
                new ObjectParameter("inmonto", inmonto) :
                new ObjectParameter("inmonto", typeof(decimal));
    
            var incodigo_productoParameter = incodigo_producto.HasValue ?
                new ObjectParameter("incodigo_producto", incodigo_producto) :
                new ObjectParameter("incodigo_producto", typeof(int));
    
            var incantidad_productoParameter = incantidad_producto.HasValue ?
                new ObjectParameter("incantidad_producto", incantidad_producto) :
                new ObjectParameter("incantidad_producto", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Crear_Detalle_Venta", innombre_clienteParameter, incarnet_empleadoParameter, innombre_ferreteriaParameter, infechaParameter, inmontoParameter, incodigo_productoParameter, incantidad_productoParameter);
        }
    
        public virtual int Crear_Direccion(string indescripcion, System.Data.Entity.Spatial.DbGeometry in_ubicacion)
        {
            var indescripcionParameter = indescripcion != null ?
                new ObjectParameter("indescripcion", indescripcion) :
                new ObjectParameter("indescripcion", typeof(string));
    
            var in_ubicacionParameter = in_ubicacion != null ?
                new ObjectParameter("in_ubicacion", in_ubicacion) :
                new ObjectParameter("in_ubicacion", typeof(System.Data.Entity.Spatial.DbGeometry));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Crear_Direccion", indescripcionParameter, in_ubicacionParameter);
        }
    
        public virtual int Crear_Direccion_x_Cliente(string innombre_cliente, System.Data.Entity.Spatial.DbGeometry inubicacion)
        {
            var innombre_clienteParameter = innombre_cliente != null ?
                new ObjectParameter("innombre_cliente", innombre_cliente) :
                new ObjectParameter("innombre_cliente", typeof(string));
    
            var inubicacionParameter = inubicacion != null ?
                new ObjectParameter("inubicacion", inubicacion) :
                new ObjectParameter("inubicacion", typeof(System.Data.Entity.Spatial.DbGeometry));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Crear_Direccion_x_Cliente", innombre_clienteParameter, inubicacionParameter);
        }
    
        public virtual int Crear_Empleado(string indescripcion_tipo_empleado, string innombre_empleado, Nullable<System.DateTime> inFechaIngreso, Nullable<int> incarnet, Nullable<decimal> insalario, Nullable<int> invacaciones)
        {
            var indescripcion_tipo_empleadoParameter = indescripcion_tipo_empleado != null ?
                new ObjectParameter("indescripcion_tipo_empleado", indescripcion_tipo_empleado) :
                new ObjectParameter("indescripcion_tipo_empleado", typeof(string));
    
            var innombre_empleadoParameter = innombre_empleado != null ?
                new ObjectParameter("innombre_empleado", innombre_empleado) :
                new ObjectParameter("innombre_empleado", typeof(string));
    
            var inFechaIngresoParameter = inFechaIngreso.HasValue ?
                new ObjectParameter("inFechaIngreso", inFechaIngreso) :
                new ObjectParameter("inFechaIngreso", typeof(System.DateTime));
    
            var incarnetParameter = incarnet.HasValue ?
                new ObjectParameter("incarnet", incarnet) :
                new ObjectParameter("incarnet", typeof(int));
    
            var insalarioParameter = insalario.HasValue ?
                new ObjectParameter("insalario", insalario) :
                new ObjectParameter("insalario", typeof(decimal));
    
            var invacacionesParameter = invacaciones.HasValue ?
                new ObjectParameter("invacaciones", invacaciones) :
                new ObjectParameter("invacaciones", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Crear_Empleado", indescripcion_tipo_empleadoParameter, innombre_empleadoParameter, inFechaIngresoParameter, incarnetParameter, insalarioParameter, invacacionesParameter);
        }
    
        public virtual int Crear_Empleado_x_Ferreteria(Nullable<int> incarnet_empleado, string innombre_ferreteria)
        {
            var incarnet_empleadoParameter = incarnet_empleado.HasValue ?
                new ObjectParameter("incarnet_empleado", incarnet_empleado) :
                new ObjectParameter("incarnet_empleado", typeof(int));
    
            var innombre_ferreteriaParameter = innombre_ferreteria != null ?
                new ObjectParameter("innombre_ferreteria", innombre_ferreteria) :
                new ObjectParameter("innombre_ferreteria", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Crear_Empleado_x_Ferreteria", incarnet_empleadoParameter, innombre_ferreteriaParameter);
        }
    
        public virtual int Crear_Entrega(string inplaca_vehiculo, string indescripcion_ruta, Nullable<System.DateTime> infecha)
        {
            var inplaca_vehiculoParameter = inplaca_vehiculo != null ?
                new ObjectParameter("inplaca_vehiculo", inplaca_vehiculo) :
                new ObjectParameter("inplaca_vehiculo", typeof(string));
    
            var indescripcion_rutaParameter = indescripcion_ruta != null ?
                new ObjectParameter("indescripcion_ruta", indescripcion_ruta) :
                new ObjectParameter("indescripcion_ruta", typeof(string));
    
            var infechaParameter = infecha.HasValue ?
                new ObjectParameter("infecha", infecha) :
                new ObjectParameter("infecha", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Crear_Entrega", inplaca_vehiculoParameter, indescripcion_rutaParameter, infechaParameter);
        }
    
        public virtual int Crear_Estante(Nullable<int> innumero, Nullable<int> innumero_pasillo, string indescripdepartamento, string innombre_ferreteria)
        {
            var innumeroParameter = innumero.HasValue ?
                new ObjectParameter("innumero", innumero) :
                new ObjectParameter("innumero", typeof(int));
    
            var innumero_pasilloParameter = innumero_pasillo.HasValue ?
                new ObjectParameter("innumero_pasillo", innumero_pasillo) :
                new ObjectParameter("innumero_pasillo", typeof(int));
    
            var indescripdepartamentoParameter = indescripdepartamento != null ?
                new ObjectParameter("indescripdepartamento", indescripdepartamento) :
                new ObjectParameter("indescripdepartamento", typeof(string));
    
            var innombre_ferreteriaParameter = innombre_ferreteria != null ?
                new ObjectParameter("innombre_ferreteria", innombre_ferreteria) :
                new ObjectParameter("innombre_ferreteria", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Crear_Estante", innumeroParameter, innumero_pasilloParameter, indescripdepartamentoParameter, innombre_ferreteriaParameter);
        }
    
        public virtual int Crear_Estante_x_Producto(Nullable<int> innumero_estante, Nullable<int> incodigo_producto, Nullable<int> innumero_pasillo, string indescripdepartamento, string innombre_ferreteria)
        {
            var innumero_estanteParameter = innumero_estante.HasValue ?
                new ObjectParameter("innumero_estante", innumero_estante) :
                new ObjectParameter("innumero_estante", typeof(int));
    
            var incodigo_productoParameter = incodigo_producto.HasValue ?
                new ObjectParameter("incodigo_producto", incodigo_producto) :
                new ObjectParameter("incodigo_producto", typeof(int));
    
            var innumero_pasilloParameter = innumero_pasillo.HasValue ?
                new ObjectParameter("innumero_pasillo", innumero_pasillo) :
                new ObjectParameter("innumero_pasillo", typeof(int));
    
            var indescripdepartamentoParameter = indescripdepartamento != null ?
                new ObjectParameter("indescripdepartamento", indescripdepartamento) :
                new ObjectParameter("indescripdepartamento", typeof(string));
    
            var innombre_ferreteriaParameter = innombre_ferreteria != null ?
                new ObjectParameter("innombre_ferreteria", innombre_ferreteria) :
                new ObjectParameter("innombre_ferreteria", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Crear_Estante_x_Producto", innumero_estanteParameter, incodigo_productoParameter, innumero_pasilloParameter, indescripdepartamentoParameter, innombre_ferreteriaParameter);
        }
    
        public virtual int Crear_Ferreteria(string indescripcion, System.Data.Entity.Spatial.DbGeometry in_ubicacion)
        {
            var indescripcionParameter = indescripcion != null ?
                new ObjectParameter("indescripcion", indescripcion) :
                new ObjectParameter("indescripcion", typeof(string));
    
            var in_ubicacionParameter = in_ubicacion != null ?
                new ObjectParameter("in_ubicacion", in_ubicacion) :
                new ObjectParameter("in_ubicacion", typeof(System.Data.Entity.Spatial.DbGeometry));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Crear_Ferreteria", indescripcionParameter, in_ubicacionParameter);
        }
    
        public virtual int Crear_Flotilla(string innombre_ferreteria)
        {
            var innombre_ferreteriaParameter = innombre_ferreteria != null ?
                new ObjectParameter("innombre_ferreteria", innombre_ferreteria) :
                new ObjectParameter("innombre_ferreteria", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Crear_Flotilla", innombre_ferreteriaParameter);
        }
    
        public virtual int Crear_Garantia(string indescripcion, Nullable<int> in_tiempo_garantia)
        {
            var indescripcionParameter = indescripcion != null ?
                new ObjectParameter("indescripcion", indescripcion) :
                new ObjectParameter("indescripcion", typeof(string));
    
            var in_tiempo_garantiaParameter = in_tiempo_garantia.HasValue ?
                new ObjectParameter("in_tiempo_garantia", in_tiempo_garantia) :
                new ObjectParameter("in_tiempo_garantia", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Crear_Garantia", indescripcionParameter, in_tiempo_garantiaParameter);
        }
    
        public virtual int Crear_Inventario_Bodega(string innombre_producto, string innombre_bodega, Nullable<int> incantidad)
        {
            var innombre_productoParameter = innombre_producto != null ?
                new ObjectParameter("innombre_producto", innombre_producto) :
                new ObjectParameter("innombre_producto", typeof(string));
    
            var innombre_bodegaParameter = innombre_bodega != null ?
                new ObjectParameter("innombre_bodega", innombre_bodega) :
                new ObjectParameter("innombre_bodega", typeof(string));
    
            var incantidadParameter = incantidad.HasValue ?
                new ObjectParameter("incantidad", incantidad) :
                new ObjectParameter("incantidad", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Crear_Inventario_Bodega", innombre_productoParameter, innombre_bodegaParameter, incantidadParameter);
        }
    
        public virtual int Crear_Inventario_Ferreteria(string innombre_producto, string innombre_ferreteria, Nullable<int> incantidad)
        {
            var innombre_productoParameter = innombre_producto != null ?
                new ObjectParameter("innombre_producto", innombre_producto) :
                new ObjectParameter("innombre_producto", typeof(string));
    
            var innombre_ferreteriaParameter = innombre_ferreteria != null ?
                new ObjectParameter("innombre_ferreteria", innombre_ferreteria) :
                new ObjectParameter("innombre_ferreteria", typeof(string));
    
            var incantidadParameter = incantidad.HasValue ?
                new ObjectParameter("incantidad", incantidad) :
                new ObjectParameter("incantidad", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Crear_Inventario_Ferreteria", innombre_productoParameter, innombre_ferreteriaParameter, incantidadParameter);
        }
    
        public virtual int Crear_Marca(string innombre)
        {
            var innombreParameter = innombre != null ?
                new ObjectParameter("innombre", innombre) :
                new ObjectParameter("innombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Crear_Marca", innombreParameter);
        }
    
        public virtual int Crear_Pasillo(Nullable<int> innumero)
        {
            var innumeroParameter = innumero.HasValue ?
                new ObjectParameter("innumero", innumero) :
                new ObjectParameter("innumero", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Crear_Pasillo", innumeroParameter);
        }
    
        public virtual int Crear_Pasillo_x_Departamento(Nullable<int> innumero_pasillo, string indescripdepartamento, string innombre_ferreteria)
        {
            var innumero_pasilloParameter = innumero_pasillo.HasValue ?
                new ObjectParameter("innumero_pasillo", innumero_pasillo) :
                new ObjectParameter("innumero_pasillo", typeof(int));
    
            var indescripdepartamentoParameter = indescripdepartamento != null ?
                new ObjectParameter("indescripdepartamento", indescripdepartamento) :
                new ObjectParameter("indescripdepartamento", typeof(string));
    
            var innombre_ferreteriaParameter = innombre_ferreteria != null ?
                new ObjectParameter("innombre_ferreteria", innombre_ferreteria) :
                new ObjectParameter("innombre_ferreteria", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Crear_Pasillo_x_Departamento", innumero_pasilloParameter, indescripdepartamentoParameter, innombre_ferreteriaParameter);
        }
    
        public virtual int Crear_Provedor(string innombre, Nullable<int> in_telefono)
        {
            var innombreParameter = innombre != null ?
                new ObjectParameter("innombre", innombre) :
                new ObjectParameter("innombre", typeof(string));
    
            var in_telefonoParameter = in_telefono.HasValue ?
                new ObjectParameter("in_telefono", in_telefono) :
                new ObjectParameter("in_telefono", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Crear_Provedor", innombreParameter, in_telefonoParameter);
        }
    
        public virtual int Crear_Punto(System.Data.Entity.Spatial.DbGeometry inubicacion)
        {
            var inubicacionParameter = inubicacion != null ?
                new ObjectParameter("inubicacion", inubicacion) :
                new ObjectParameter("inubicacion", typeof(System.Data.Entity.Spatial.DbGeometry));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Crear_Punto", inubicacionParameter);
        }
    
        public virtual int Crear_Punto_x_Ruta(System.Data.Entity.Spatial.DbGeometry inubicacion_punto, string indescripcion_ruta)
        {
            var inubicacion_puntoParameter = inubicacion_punto != null ?
                new ObjectParameter("inubicacion_punto", inubicacion_punto) :
                new ObjectParameter("inubicacion_punto", typeof(System.Data.Entity.Spatial.DbGeometry));
    
            var indescripcion_rutaParameter = indescripcion_ruta != null ?
                new ObjectParameter("indescripcion_ruta", indescripcion_ruta) :
                new ObjectParameter("indescripcion_ruta", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Crear_Punto_x_Ruta", inubicacion_puntoParameter, indescripcion_rutaParameter);
        }
    
        public virtual int Crear_Ruta(string indescripcion)
        {
            var indescripcionParameter = indescripcion != null ?
                new ObjectParameter("indescripcion", indescripcion) :
                new ObjectParameter("indescripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Crear_Ruta", indescripcionParameter);
        }
    
        public virtual int Crear_Tipo_Empleado(string indescripcion)
        {
            var indescripcionParameter = indescripcion != null ?
                new ObjectParameter("indescripcion", indescripcion) :
                new ObjectParameter("indescripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Crear_Tipo_Empleado", indescripcionParameter);
        }
    
        public virtual int Crear_Utilidad(string indescripcion)
        {
            var indescripcionParameter = indescripcion != null ?
                new ObjectParameter("indescripcion", indescripcion) :
                new ObjectParameter("indescripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Crear_Utilidad", indescripcionParameter);
        }
    
        public virtual int Crear_Utilidad_x_Producto(string innombre_producto, string indescripcion_utilidad)
        {
            var innombre_productoParameter = innombre_producto != null ?
                new ObjectParameter("innombre_producto", innombre_producto) :
                new ObjectParameter("innombre_producto", typeof(string));
    
            var indescripcion_utilidadParameter = indescripcion_utilidad != null ?
                new ObjectParameter("indescripcion_utilidad", indescripcion_utilidad) :
                new ObjectParameter("indescripcion_utilidad", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Crear_Utilidad_x_Producto", innombre_productoParameter, indescripcion_utilidadParameter);
        }
    
        public virtual int Crear_Vehiculo(string inplaca_vehiculo, string indescripcion, Nullable<int> incapcidad_tanque_gasolina, string innombre_ferreteria, Nullable<int> incarnet_empleado)
        {
            var inplaca_vehiculoParameter = inplaca_vehiculo != null ?
                new ObjectParameter("inplaca_vehiculo", inplaca_vehiculo) :
                new ObjectParameter("inplaca_vehiculo", typeof(string));
    
            var indescripcionParameter = indescripcion != null ?
                new ObjectParameter("indescripcion", indescripcion) :
                new ObjectParameter("indescripcion", typeof(string));
    
            var incapcidad_tanque_gasolinaParameter = incapcidad_tanque_gasolina.HasValue ?
                new ObjectParameter("incapcidad_tanque_gasolina", incapcidad_tanque_gasolina) :
                new ObjectParameter("incapcidad_tanque_gasolina", typeof(int));
    
            var innombre_ferreteriaParameter = innombre_ferreteria != null ?
                new ObjectParameter("innombre_ferreteria", innombre_ferreteria) :
                new ObjectParameter("innombre_ferreteria", typeof(string));
    
            var incarnet_empleadoParameter = incarnet_empleado.HasValue ?
                new ObjectParameter("incarnet_empleado", incarnet_empleado) :
                new ObjectParameter("incarnet_empleado", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Crear_Vehiculo", inplaca_vehiculoParameter, indescripcionParameter, incapcidad_tanque_gasolinaParameter, innombre_ferreteriaParameter, incarnet_empleadoParameter);
        }
    
        public virtual int Crear_Venta(string innombre_cliente, Nullable<int> incarnet_empleado, string innombre_ferreteria, Nullable<System.DateTime> infecha, Nullable<decimal> inmonto)
        {
            var innombre_clienteParameter = innombre_cliente != null ?
                new ObjectParameter("innombre_cliente", innombre_cliente) :
                new ObjectParameter("innombre_cliente", typeof(string));
    
            var incarnet_empleadoParameter = incarnet_empleado.HasValue ?
                new ObjectParameter("incarnet_empleado", incarnet_empleado) :
                new ObjectParameter("incarnet_empleado", typeof(int));
    
            var innombre_ferreteriaParameter = innombre_ferreteria != null ?
                new ObjectParameter("innombre_ferreteria", innombre_ferreteria) :
                new ObjectParameter("innombre_ferreteria", typeof(string));
    
            var infechaParameter = infecha.HasValue ?
                new ObjectParameter("infecha", infecha) :
                new ObjectParameter("infecha", typeof(System.DateTime));
    
            var inmontoParameter = inmonto.HasValue ?
                new ObjectParameter("inmonto", inmonto) :
                new ObjectParameter("inmonto", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Crear_Venta", innombre_clienteParameter, incarnet_empleadoParameter, innombre_ferreteriaParameter, infechaParameter, inmontoParameter);
        }
    
        public virtual int Eliminar_Amonestacion(string indescripcion)
        {
            var indescripcionParameter = indescripcion != null ?
                new ObjectParameter("indescripcion", indescripcion) :
                new ObjectParameter("indescripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Eliminar_Amonestacion", indescripcionParameter);
        }
    
        public virtual int Eliminar_Amonestacion_x_Empleado(string innombre_amonestacion, Nullable<int> incarnet_empleado, string indescripcion)
        {
            var innombre_amonestacionParameter = innombre_amonestacion != null ?
                new ObjectParameter("innombre_amonestacion", innombre_amonestacion) :
                new ObjectParameter("innombre_amonestacion", typeof(string));
    
            var incarnet_empleadoParameter = incarnet_empleado.HasValue ?
                new ObjectParameter("incarnet_empleado", incarnet_empleado) :
                new ObjectParameter("incarnet_empleado", typeof(int));
    
            var indescripcionParameter = indescripcion != null ?
                new ObjectParameter("indescripcion", indescripcion) :
                new ObjectParameter("indescripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Eliminar_Amonestacion_x_Empleado", innombre_amonestacionParameter, incarnet_empleadoParameter, indescripcionParameter);
        }
    
        public virtual int Eliminar_Aspecto_Tecnico(string indescripcion)
        {
            var indescripcionParameter = indescripcion != null ?
                new ObjectParameter("indescripcion", indescripcion) :
                new ObjectParameter("indescripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Eliminar_Aspecto_Tecnico", indescripcionParameter);
        }
    
        public virtual int Eliminar_Aspecto_Tecnico_x_Producto(string innombre_producto, string indescripcion_aspecto_tecnico)
        {
            var innombre_productoParameter = innombre_producto != null ?
                new ObjectParameter("innombre_producto", innombre_producto) :
                new ObjectParameter("innombre_producto", typeof(string));
    
            var indescripcion_aspecto_tecnicoParameter = indescripcion_aspecto_tecnico != null ?
                new ObjectParameter("indescripcion_aspecto_tecnico", indescripcion_aspecto_tecnico) :
                new ObjectParameter("indescripcion_aspecto_tecnico", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Eliminar_Aspecto_Tecnico_x_Producto", innombre_productoParameter, indescripcion_aspecto_tecnicoParameter);
        }
    
        public virtual int Eliminar_Bodega(string indescripcion)
        {
            var indescripcionParameter = indescripcion != null ?
                new ObjectParameter("indescripcion", indescripcion) :
                new ObjectParameter("indescripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Eliminar_Bodega", indescripcionParameter);
        }
    
        public virtual int Eliminar_Cliente(string innombre)
        {
            var innombreParameter = innombre != null ?
                new ObjectParameter("innombre", innombre) :
                new ObjectParameter("innombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Eliminar_Cliente", innombreParameter);
        }
    
        public virtual int Eliminar_Cliente_x_Ferreteria(string innombre_cliente, string innombre_ferreteria)
        {
            var innombre_clienteParameter = innombre_cliente != null ?
                new ObjectParameter("innombre_cliente", innombre_cliente) :
                new ObjectParameter("innombre_cliente", typeof(string));
    
            var innombre_ferreteriaParameter = innombre_ferreteria != null ?
                new ObjectParameter("innombre_ferreteria", innombre_ferreteria) :
                new ObjectParameter("innombre_ferreteria", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Eliminar_Cliente_x_Ferreteria", innombre_clienteParameter, innombre_ferreteriaParameter);
        }
    
        public virtual int Eliminar_contraindicacion(string indescripcion)
        {
            var indescripcionParameter = indescripcion != null ?
                new ObjectParameter("indescripcion", indescripcion) :
                new ObjectParameter("indescripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Eliminar_contraindicacion", indescripcionParameter);
        }
    
        public virtual int Eliminar_Contraindicacion_x_Producto(string innombre_producto, string indescripcion_contraindicacion)
        {
            var innombre_productoParameter = innombre_producto != null ?
                new ObjectParameter("innombre_producto", innombre_producto) :
                new ObjectParameter("innombre_producto", typeof(string));
    
            var indescripcion_contraindicacionParameter = indescripcion_contraindicacion != null ?
                new ObjectParameter("indescripcion_contraindicacion", indescripcion_contraindicacion) :
                new ObjectParameter("indescripcion_contraindicacion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Eliminar_Contraindicacion_x_Producto", innombre_productoParameter, indescripcion_contraindicacionParameter);
        }
    
        public virtual int Eliminar_Cuidado(string indescripcion)
        {
            var indescripcionParameter = indescripcion != null ?
                new ObjectParameter("indescripcion", indescripcion) :
                new ObjectParameter("indescripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Eliminar_Cuidado", indescripcionParameter);
        }
    
        public virtual int Eliminar_Cuidado_x_Producto(string innombre_producto, string indescripcion_cuidado)
        {
            var innombre_productoParameter = innombre_producto != null ?
                new ObjectParameter("innombre_producto", innombre_producto) :
                new ObjectParameter("innombre_producto", typeof(string));
    
            var indescripcion_cuidadoParameter = indescripcion_cuidado != null ?
                new ObjectParameter("indescripcion_cuidado", indescripcion_cuidado) :
                new ObjectParameter("indescripcion_cuidado", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Eliminar_Cuidado_x_Producto", innombre_productoParameter, indescripcion_cuidadoParameter);
        }
    
        public virtual int Eliminar_Departamento(string innombre)
        {
            var innombreParameter = innombre != null ?
                new ObjectParameter("innombre", innombre) :
                new ObjectParameter("innombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Eliminar_Departamento", innombreParameter);
        }
    
        public virtual int Eliminar_Direccion(string indescripcion)
        {
            var indescripcionParameter = indescripcion != null ?
                new ObjectParameter("indescripcion", indescripcion) :
                new ObjectParameter("indescripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Eliminar_Direccion", indescripcionParameter);
        }
    
        public virtual int Eliminar_Direccion_x_Cliente(string innombre_cliente, System.Data.Entity.Spatial.DbGeometry inubicacion)
        {
            var innombre_clienteParameter = innombre_cliente != null ?
                new ObjectParameter("innombre_cliente", innombre_cliente) :
                new ObjectParameter("innombre_cliente", typeof(string));
    
            var inubicacionParameter = inubicacion != null ?
                new ObjectParameter("inubicacion", inubicacion) :
                new ObjectParameter("inubicacion", typeof(System.Data.Entity.Spatial.DbGeometry));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Eliminar_Direccion_x_Cliente", innombre_clienteParameter, inubicacionParameter);
        }
    
        public virtual int Eliminar_Empleado(string innombre)
        {
            var innombreParameter = innombre != null ?
                new ObjectParameter("innombre", innombre) :
                new ObjectParameter("innombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Eliminar_Empleado", innombreParameter);
        }
    
        public virtual int Eliminar_Empleado_x_Ferreteria(Nullable<int> incarnet_empleado, string innombre_ferreteria)
        {
            var incarnet_empleadoParameter = incarnet_empleado.HasValue ?
                new ObjectParameter("incarnet_empleado", incarnet_empleado) :
                new ObjectParameter("incarnet_empleado", typeof(int));
    
            var innombre_ferreteriaParameter = innombre_ferreteria != null ?
                new ObjectParameter("innombre_ferreteria", innombre_ferreteria) :
                new ObjectParameter("innombre_ferreteria", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Eliminar_Empleado_x_Ferreteria", incarnet_empleadoParameter, innombre_ferreteriaParameter);
        }
    
        public virtual int Eliminar_Ferreteria(string indescripcion)
        {
            var indescripcionParameter = indescripcion != null ?
                new ObjectParameter("indescripcion", indescripcion) :
                new ObjectParameter("indescripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Eliminar_Ferreteria", indescripcionParameter);
        }
    
        public virtual int Eliminar_Garantia(string indescripcion)
        {
            var indescripcionParameter = indescripcion != null ?
                new ObjectParameter("indescripcion", indescripcion) :
                new ObjectParameter("indescripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Eliminar_Garantia", indescripcionParameter);
        }
    
        public virtual int Eliminar_Inventario_Ferreteria(string innombre_producto, string innombre_ferreteria, Nullable<int> incantidad)
        {
            var innombre_productoParameter = innombre_producto != null ?
                new ObjectParameter("innombre_producto", innombre_producto) :
                new ObjectParameter("innombre_producto", typeof(string));
    
            var innombre_ferreteriaParameter = innombre_ferreteria != null ?
                new ObjectParameter("innombre_ferreteria", innombre_ferreteria) :
                new ObjectParameter("innombre_ferreteria", typeof(string));
    
            var incantidadParameter = incantidad.HasValue ?
                new ObjectParameter("incantidad", incantidad) :
                new ObjectParameter("incantidad", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Eliminar_Inventario_Ferreteria", innombre_productoParameter, innombre_ferreteriaParameter, incantidadParameter);
        }
    
        public virtual int Eliminar_Marca(string innombre)
        {
            var innombreParameter = innombre != null ?
                new ObjectParameter("innombre", innombre) :
                new ObjectParameter("innombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Eliminar_Marca", innombreParameter);
        }
    
        public virtual int Eliminar_Pasillo(Nullable<int> innumero)
        {
            var innumeroParameter = innumero.HasValue ?
                new ObjectParameter("innumero", innumero) :
                new ObjectParameter("innumero", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Eliminar_Pasillo", innumeroParameter);
        }
    
        public virtual int Eliminar_Producto(Nullable<int> incodigo)
        {
            var incodigoParameter = incodigo.HasValue ?
                new ObjectParameter("incodigo", incodigo) :
                new ObjectParameter("incodigo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Eliminar_Producto", incodigoParameter);
        }
    
        public virtual int Eliminar_Provedor(string innombre)
        {
            var innombreParameter = innombre != null ?
                new ObjectParameter("innombre", innombre) :
                new ObjectParameter("innombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Eliminar_Provedor", innombreParameter);
        }
    
        public virtual int Eliminar_Ruta(string indescripcion)
        {
            var indescripcionParameter = indescripcion != null ?
                new ObjectParameter("indescripcion", indescripcion) :
                new ObjectParameter("indescripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Eliminar_Ruta", indescripcionParameter);
        }
    
        public virtual int Eliminar_Tipo_Empleado(string indescripcion)
        {
            var indescripcionParameter = indescripcion != null ?
                new ObjectParameter("indescripcion", indescripcion) :
                new ObjectParameter("indescripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Eliminar_Tipo_Empleado", indescripcionParameter);
        }
    
        public virtual int Eliminar_Utilidad(string indescripcion)
        {
            var indescripcionParameter = indescripcion != null ?
                new ObjectParameter("indescripcion", indescripcion) :
                new ObjectParameter("indescripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Eliminar_Utilidad", indescripcionParameter);
        }
    
        public virtual int Eliminar_Utilidad_x_Producto(string innombre_producto, string indescripcion_utilidad)
        {
            var innombre_productoParameter = innombre_producto != null ?
                new ObjectParameter("innombre_producto", innombre_producto) :
                new ObjectParameter("innombre_producto", typeof(string));
    
            var indescripcion_utilidadParameter = indescripcion_utilidad != null ?
                new ObjectParameter("indescripcion_utilidad", indescripcion_utilidad) :
                new ObjectParameter("indescripcion_utilidad", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Eliminar_Utilidad_x_Producto", innombre_productoParameter, indescripcion_utilidadParameter);
        }
    
        public virtual ObjectResult<string> Leer_Amonestacion(string indescripcion)
        {
            var indescripcionParameter = indescripcion != null ?
                new ObjectParameter("indescripcion", indescripcion) :
                new ObjectParameter("indescripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("Leer_Amonestacion", indescripcionParameter);
        }
    
        public virtual ObjectResult<string> Leer_Aspecto_Tecnico(string indescripcion)
        {
            var indescripcionParameter = indescripcion != null ?
                new ObjectParameter("indescripcion", indescripcion) :
                new ObjectParameter("indescripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("Leer_Aspecto_Tecnico", indescripcionParameter);
        }
    
        public virtual ObjectResult<Leer_Bodega_Result> Leer_Bodega(string indescripcion)
        {
            var indescripcionParameter = indescripcion != null ?
                new ObjectParameter("indescripcion", indescripcion) :
                new ObjectParameter("indescripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Leer_Bodega_Result>("Leer_Bodega", indescripcionParameter);
        }
    
        public virtual int Leer_Cliente(string innombre)
        {
            var innombreParameter = innombre != null ?
                new ObjectParameter("innombre", innombre) :
                new ObjectParameter("innombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Leer_Cliente", innombreParameter);
        }
    
        public virtual ObjectResult<string> Leer_contraindicacion(string indescripcion)
        {
            var indescripcionParameter = indescripcion != null ?
                new ObjectParameter("indescripcion", indescripcion) :
                new ObjectParameter("indescripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("Leer_contraindicacion", indescripcionParameter);
        }
    
        public virtual ObjectResult<string> Leer_Cuidado(string indescripcion)
        {
            var indescripcionParameter = indescripcion != null ?
                new ObjectParameter("indescripcion", indescripcion) :
                new ObjectParameter("indescripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("Leer_Cuidado", indescripcionParameter);
        }
    
        public virtual ObjectResult<string> Leer_Departamento(string innombre)
        {
            var innombreParameter = innombre != null ?
                new ObjectParameter("innombre", innombre) :
                new ObjectParameter("innombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("Leer_Departamento", innombreParameter);
        }
    
        public virtual int Leer_Direccion(string indescripcion)
        {
            var indescripcionParameter = indescripcion != null ?
                new ObjectParameter("indescripcion", indescripcion) :
                new ObjectParameter("indescripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Leer_Direccion", indescripcionParameter);
        }
    
        public virtual ObjectResult<Leer_Empleado_Result> Leer_Empleado(string innombre)
        {
            var innombreParameter = innombre != null ?
                new ObjectParameter("innombre", innombre) :
                new ObjectParameter("innombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Leer_Empleado_Result>("Leer_Empleado", innombreParameter);
        }
    
        public virtual ObjectResult<Leer_Ferreteria_Result> Leer_Ferreteria(string indescripcion)
        {
            var indescripcionParameter = indescripcion != null ?
                new ObjectParameter("indescripcion", indescripcion) :
                new ObjectParameter("indescripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Leer_Ferreteria_Result>("Leer_Ferreteria", indescripcionParameter);
        }
    
        public virtual ObjectResult<Leer_Garantia_Result> Leer_Garantia(string indescripcion)
        {
            var indescripcionParameter = indescripcion != null ?
                new ObjectParameter("indescripcion", indescripcion) :
                new ObjectParameter("indescripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Leer_Garantia_Result>("Leer_Garantia", indescripcionParameter);
        }
    
        public virtual ObjectResult<string> Leer_Marca(string innombre)
        {
            var innombreParameter = innombre != null ?
                new ObjectParameter("innombre", innombre) :
                new ObjectParameter("innombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("Leer_Marca", innombreParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Leer_Pasillo(Nullable<int> innumero)
        {
            var innumeroParameter = innumero.HasValue ?
                new ObjectParameter("innumero", innumero) :
                new ObjectParameter("innumero", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Leer_Pasillo", innumeroParameter);
        }
    
        public virtual int Leer_Provedor(string innombre)
        {
            var innombreParameter = innombre != null ?
                new ObjectParameter("innombre", innombre) :
                new ObjectParameter("innombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Leer_Provedor", innombreParameter);
        }
    
        public virtual int Leer_Ruta(string indescripcion)
        {
            var indescripcionParameter = indescripcion != null ?
                new ObjectParameter("indescripcion", indescripcion) :
                new ObjectParameter("indescripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Leer_Ruta", indescripcionParameter);
        }
    
        public virtual ObjectResult<string> Leer_Tipo_Empleado(string indescripcion)
        {
            var indescripcionParameter = indescripcion != null ?
                new ObjectParameter("indescripcion", indescripcion) :
                new ObjectParameter("indescripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("Leer_Tipo_Empleado", indescripcionParameter);
        }
    
        public virtual ObjectResult<string> Leer_Utilidad(string indescripcion)
        {
            var indescripcionParameter = indescripcion != null ?
                new ObjectParameter("indescripcion", indescripcion) :
                new ObjectParameter("indescripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("Leer_Utilidad", indescripcionParameter);
        }
    }
}
