//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto_x_Estante
    {
        public int id_producto_x_estante { get; set; }
        public int id_estante { get; set; }
        public int id_producto { get; set; }
        public bool activo { get; set; }
    
        public virtual Estante Estante { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
