//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Producto()
        {
            this.Detalle_Lista_Deseos = new HashSet<Detalle_Lista_Deseos>();
            this.Detalle_Venta = new HashSet<Detalle_Venta>();
            this.Inventario_Bodega = new HashSet<Inventario_Bodega>();
            this.Inventario_Ferreteria = new HashSet<Inventario_Ferreteria>();
            this.Producto_x_Estante = new HashSet<Producto_x_Estante>();
        }
    
        public int id_producto { get; set; }
        public string descripcion { get; set; }
        public byte[] foto { get; set; }
        public decimal precio { get; set; }
        public int id_marca { get; set; }
        public int codigo { get; set; }
        public int id_garantia { get; set; }
        public bool activo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detalle_Lista_Deseos> Detalle_Lista_Deseos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detalle_Venta> Detalle_Venta { get; set; }
        public virtual Garantia Garantia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inventario_Bodega> Inventario_Bodega { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inventario_Ferreteria> Inventario_Ferreteria { get; set; }
        public virtual Marca Marca { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Producto_x_Estante> Producto_x_Estante { get; set; }
        public virtual ProductoDetalles ProductoDetalles { get; set; }
    }
}
