//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductoDetalles
    {
        public int id_producto { get; set; }
        public int id_provedor { get; set; }
        public int id_aspectos_tecnicos { get; set; }
        public int id_contraindicaciones { get; set; }
        public int id_utilidades { get; set; }
        public int id_cuidados { get; set; }
    
        public virtual Producto Producto { get; set; }
    }
}
