//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Venta()
        {
            this.Detalle_Venta = new HashSet<Detalle_Venta>();
        }
    
        public int id_venta { get; set; }
        public int id_cliente { get; set; }
        public int id_tipo_venta { get; set; }
        public int id_ferreteria { get; set; }
        public int id_vendedor { get; set; }
        public System.DateTime fecha { get; set; }
        public decimal monto { get; set; }
        public bool activo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detalle_Venta> Detalle_Venta { get; set; }
        public virtual Empleado Empleado { get; set; }
        public virtual Ferreteria Ferreteria { get; set; }
        public virtual Tipo_venta Tipo_venta { get; set; }
    }
}
